name = "DirWalkers"
uuid = "e22505fa-d5cb-4f7b-9088-d54cc7e0689e"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.2.0"

[weakdeps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[extensions]
DistributedDirWalkersExt = "Distributed"
